POST http://localhost:3000/game/save
Content-Type: application/json

{
    "uid":"12345",
    "score":"0",
    "name":"pawat"
}
###
GET http://localhost:3000/game/getstart
Content-Type: application/json

{

}
###
GET http://localhost:3000/game/getranking?uid=1234
Content-Type: application/json

{

}
###
POST http://localhost:3000/dashboard/login
Content-Type: application/json

{
    "username":"admin",
    "password":"password"
}
###
GET http://localhost:3000/dashboard/profile
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkRnRnVTlPTXVLRldJWDFCVVdoY2xWZVg4UXo3N3RTUG9xbm5SanN0TGN2d1lIWEJ0NEZoZXEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTM0Nzk3NDcsImV4cCI6MTcxMzU2NjE0N30.NjmiXaQys6EkH3toxW9sKUhxaDVFF_Sbsms_SOAwQ3w